export interface DataType {
    key: React.Key;
    Languages: string;
    GTMTotal_WOEbooks: string | null;
    GTMTotal_WEbooks: string | null;
    PVH_Previous: string | null;
    PVH_Added: string | null;
    PVH_Withdrawn: string | null;
    PVH_SubTotal: string | null;
    OMH_Microform: string | null;
    OMH_Cartographic: string | null;
    OMH_Audio: string | null;
    OMH_FilmVideo: string | null;
    OMH_DVD: string | null;
    OMH_SubTotal: string | null;
    EB_PT_Previous: string | null;
    EB_PT_Add: string | null;
    EB_PT_Subtotal: string | null;
    EB_PT_NPTitles: string | null;
    EB_PT_SubTitles: string | null;
    EB_PT_TitlesTotal: string | null;
    EB_PV_Previous: string | null;
    EB_PV_Add: string | null;
    EB_PV_Subtotal: string | null;
    EB_PV_NPVolumes: string | null;
    EB_PV_SubVolumes: string | null;
    EB_PV_VolumesTotal: string | null;
    UB_Mat_Total: string | null;
    MGAdd_VolumesPurchased: string | null;
    MGAdd_VolumesNonPurchased: string | null;
    MGAdd_VolumesTotal: string | null;
    MGAdd_TitlesPurchased: string | null;
    MGAdd_TitlesNonPurchased: string | null;
    MGAdd_TitlesTotal: string | null;
  }