export type SinglePersonnelSupportType = {
  id: number;
  entryid: string | null;
  libraryyear: number | null;
  psfnotes: string | null;
  psfosacquisition: boolean | null;
  psfosprocessing: boolean | null;
  psfothers: number | null;
  psfprofessional_chinese: number | null;
  psfprofessional_eastasian: number | null;
  psfprofessional_japanese: number | null;
  psfprofessional_korean: number | null;
  psfprofessional_subtotal: number | null;
  psfstudent_assistants_chinese: number | null;
  psfstudent_assistants_eastasian: number | null;
  psfstudent_assistants_japanese: number | null;
  psfstudent_assistants_korean: number | null;
  psfstudent_assistants_subtotal: number | null;
  psfsupport_staff_chinese: number | null;
  psfsupport_staff_eastasian: number | null;
  psfsupport_staff_japanese: number | null;
  psfsupport_staff_korean: number | null;
  psfsupport_staff_subtotal: number | null;
  psftotal: number | null;
};
