export type SingleVolumeHoldingsType = {
  id: number;
  entryid: String | null;
  vhprevious_year_chinese: number | null;
  vhprevious_year_japanese: number | null;
  vhprevious_year_korean: number | null;
  vhprevious_year_noncjk: number | null;
  vhprevious_year_subtotal: number | null;
  vhadded_gross_chinese: number | null;
  vhadded_gross_japanese: number | null;
  vhadded_gross_korean: number | null;
  vhadded_gross_noncjk: number | null;
  vhadded_gross_subtotal: number | null;
  vhwithdrawn_chinese: number | null;
  vhwithdrawn_japanese: number | null;
  vhwithdrawn_korean: number | null;
  vhwithdrawn_noncjk: number | null;
  vhwithdrawn_subtotal: number | null;
  vh_film_chinese: number | null;
  vh_film_japanese: number | null;
  vh_film_korean: number | null;
  vh_film_subtotal: number | null;
  vh_fiche_chinese: number | null;
  vh_fiche_japanese: number | null;
  vh_fiche_korean: number | null;
  vh_fiche_subtotal: number | null;
  vh_film_fiche_chinese: number | null;
  vh_film_fiche_japanese: number | null;
  vh_film_fiche_korean: number | null;
  vh_film_fiche_subtotal: number | null;
  vhgrandtotal: number | null;
  vhnotes: String | null;
  libraryyear: number | null;
};
