// Comprehensive field mappings for all 10 forms with frontend labels
// Notes fields are handled separately at the bottom of Excel exports

export const formFieldMappings = {
  monographic: {
    'Library_Year.Library.library_name': 'Institution',
    'mapurchased_titles_chinese': 'Purchased Titles Chinese',
    'mapurchased_titles_japanese': 'Purchased Titles Japanese',
    'mapurchased_titles_korean': 'Purchased Titles Korean',
    'mapurchased_titles_noncjk': 'Purchased Titles Non-CJK',
    'mapurchased_titles_subtotal': 'Purchased Titles Subtotal',
    'mapurchased_volumes_chinese': 'Purchased Volumes Chinese',
    'mapurchased_volumes_japanese': 'Purchased Volumes Japanese',
    'mapurchased_volumes_korean': 'Purchased Volumes Korean',
    'mapurchased_volumes_noncjk': 'Purchased Volumes Non-CJK',
    'mapurchased_volumes_subtotal': 'Purchased Volumes Subtotal',
    'manonpurchased_titles_chinese': 'Non-Purchased Titles Chinese',
    'manonpurchased_titles_japanese': 'Non-Purchased Titles Japanese',
    'manonpurchased_titles_korean': 'Non-Purchased Titles Korean',
    'manonpurchased_titles_noncjk': 'Non-Purchased Titles Non-CJK',
    'manonpurchased_titles_subtotal': 'Non-Purchased Titles Subtotal',
    'manonpurchased_volumes_chinese': 'Non-Purchased Volumes Chinese',
    'manonpurchased_volumes_japanese': 'Non-Purchased Volumes Japanese',
    'manonpurchased_volumes_korean': 'Non-Purchased Volumes Korean',
    'manonpurchased_volumes_noncjk': 'Non-Purchased Volumes Non-CJK',
    'manonpurchased_volumes_subtotal': 'Non-Purchased Volumes Subtotal',
    'matotal_titles': 'Title Total',
    'matotal_volumes': 'Volume Total'
  },
  
  volumeHoldings: {
    'Library_Year.Library.library_name': 'Institution',
    'vhprevious_year_chinese': 'Previous Chinese',
    'vhprevious_year_japanese': 'Previous Japanese',
    'vhprevious_year_korean': 'Previous Korean',
    'vhprevious_year_noncjk': 'Previous Non-CJK',
    'vhprevious_year_subtotal': 'Previous Subtotal',
    'vhadded_gross_chinese': 'Added Chinese',
    'vhadded_gross_japanese': 'Added Japanese',
    'vhadded_gross_korean': 'Added Korean',
    'vhadded_gross_noncjk': 'Added Non-CJK',
    'vhadded_gross_subtotal': 'Added Subtotal',
    'vhwithdrawn_chinese': 'Withdrawn Chinese',
    'vhwithdrawn_japanese': 'Withdrawn Japanese',
    'vhwithdrawn_korean': 'Withdrawn Korean',
    'vhwithdrawn_noncjk': 'Withdrawn Non-CJK',
    'vhwithdrawn_subtotal': 'Withdrawn Subtotal',
    'vhgrandtotal': 'Grand Total (Physical Vols)'
  },
  
  serials: {
    'Library_Year.Library.library_name': 'Institution',
    's_epurchased_chinese': 'Purchased Chinese (Electronic)',
    's_epurchased_japanese': 'Purchased Japanese (Electronic)',
    's_epurchased_korean': 'Purchased Korean (Electronic)',
    's_epurchased_noncjk': 'Purchased Non-CJK (Electronic)',
    's_epurchased_subtotal': 'Electronic Purchased Subtotal',
    'spurchased_chinese': 'Purchased Chinese (Print)',
    'spurchased_japanese': 'Purchased Japanese (Print)',
    'spurchased_korean': 'Purchased Korean (Print)',
    'spurchased_noncjk': 'Purchased Non-CJK (Print)',
    'spurchased_subtotal': 'Print Purchased Subtotal',
    's_enonpurchased_chinese': 'Non-Purchased Chinese (Electronic)',
    's_enonpurchased_japanese': 'Non-Purchased Japanese (Electronic)',
    's_enonpurchased_korean': 'Non-Purchased Korean (Electronic)',
    's_enonpurchased_noncjk': 'Non-Purchased Non-CJK (Electronic)',
    's_enonpurchased_subtotal': 'Electronic Non-Purchased Subtotal',
    'snonpurchased_chinese': 'Non-Purchased Chinese (Print)',
    'snonpurchased_japanese': 'Non-Purchased Japanese (Print)',
    'snonpurchased_korean': 'Non-Purchased Korean (Print)',
    'snonpurchased_noncjk': 'Non-Purchased Non-CJK (Print)',
    'snonpurchased_subtotal': 'Print Non-Purchased Subtotal',
    's_etotal_chinese': 'Total Chinese (Electronic)',
    's_etotal_japanese': 'Total Japanese (Electronic)',
    's_etotal_korean': 'Total Korean (Electronic)',
    's_etotal_noncjk': 'Total Non-CJK (Electronic)',
    's_egrandtotal': 'Electronic Grand Total',
    'stotal_chinese': 'Total Chinese (Print)',
    'stotal_japanese': 'Total Japanese (Print)',
    'stotal_korean': 'Total Korean (Print)',
    'stotal_noncjk': 'Total Non-CJK (Print)',
    'sgrandtotal': 'Print Grand Total',
    'stotal_overall': 'Overall Grand Total'
  },
  
  otherHoldings: {
    'Library_Year.Library.library_name': 'Institution',
    'ohmicroform_chinese': 'Microform Chinese',
    'ohmicroform_japanese': 'Microform Japanese',
    'ohmicroform_korean': 'Microform Korean',
    'ohmicroform_noncjk': 'Microform Non-CJK',
    'ohmicroform_subtotal': 'Microform Subtotal',
    'ohcarto_graphic_chinese': 'Cartographic/Graphic Chinese',
    'ohcarto_graphic_japanese': 'Cartographic/Graphic Japanese',
    'ohcarto_graphic_korean': 'Cartographic/Graphic Korean',
    'ohcarto_graphic_noncjk': 'Cartographic/Graphic Non-CJK',
    'ohcarto_graphic_subtotal': 'Cartographic/Graphic Subtotal',
    'ohaudio_chinese': 'Audio Chinese',
    'ohaudio_japanese': 'Audio Japanese',
    'ohaudio_korean': 'Audio Korean',
    'ohaudio_noncjk': 'Audio Non-CJK',
    'ohaudio_subtotal': 'Audio Subtotal',
    'ohfilm_video_chinese': 'Film/Video Chinese',
    'ohfilm_video_japanese': 'Film/Video Japanese',
    'ohfilm_video_korean': 'Film/Video Korean',
    'ohfilm_video_noncjk': 'Film/Video Non-CJK',
    'ohfilm_video_subtotal': 'Film/Video Subtotal',
    'ohdvd_chinese': 'DVD Chinese',
    'ohdvd_japanese': 'DVD Japanese',
    'ohdvd_korean': 'DVD Korean',
    'ohdvd_noncjk': 'DVD Non-CJK',
    'ohdvd_subtotal': 'DVD Subtotal',
    'ohgrandtotal': 'Grand Total'
  },
  
  unprocessed: {
    'Library_Year.Library.library_name': 'Institution',
    'ubchinese': 'Unprocessed Chinese',
    'ubjapanese': 'Unprocessed Japanese',
    'ubkorean': 'Unprocessed Korean',
    'ubnoncjk': 'Unprocessed Non-CJK',
    'ubtotal': 'Unprocessed Total'
  },
  
  fiscal: {
    'Library_Year.Library.library_name': 'Institution',
    'fschinese_appropriations_monographic': 'Chinese Appropriations Monographic',
    'fschinese_appropriations_serial': 'Chinese Appropriations Serial',
    'fschinese_appropriations_other_material': 'Chinese Appropriations Other Materials',
    'fschinese_appropriations_electronic': 'Chinese Appropriations Electronic',
    'fschinese_appropriations_subtotal': 'Chinese Appropriations Subtotal',
    'fsjapanese_appropriations_monographic': 'Japanese Appropriations Monographic',
    'fsjapanese_appropriations_serial': 'Japanese Appropriations Serial',
    'fsjapanese_appropriations_other_material': 'Japanese Appropriations Other Materials',
    'fsjapanese_appropriations_electronic': 'Japanese Appropriations Electronic',
    'fsjapanese_appropriations_subtotal': 'Japanese Appropriations Subtotal',
    'fskorean_appropriations_monographic': 'Korean Appropriations Monographic',
    'fskorean_appropriations_serial': 'Korean Appropriations Serial',
    'fskorean_appropriations_other_material': 'Korean Appropriations Other Materials',
    'fskorean_appropriations_electronic': 'Korean Appropriations Electronic',
    'fskorean_appropriations_subtotal': 'Korean Appropriations Subtotal',
    'fsnoncjk_appropriations_monographic': 'Non-CJK Appropriations Monographic',
    'fsnoncjk_appropriations_serial': 'Non-CJK Appropriations Serial',
    'fsnoncjk_appropriations_other_material': 'Non-CJK Appropriations Other Materials',
    'fsnoncjk_appropriations_electronic': 'Non-CJK Appropriations Electronic',
    'fsnoncjk_appropriations_subtotal': 'Non-CJK Appropriations Subtotal',
    'fstotal_appropriations': 'Total Appropriations',
    'fsendowments_chinese': 'Endowments Chinese',
    'fsendowments_japanese': 'Endowments Japanese',
    'fsendowments_korean': 'Endowments Korean',
    'fsendowments_noncjk': 'Endowments Non-CJK',
    'fsendowments_subtotal': 'Endowments Subtotal',
    'fsgrants_chinese': 'Grants Chinese',
    'fsgrants_japanese': 'Grants Japanese',
    'fsgrants_korean': 'Grants Korean',
    'fsgrants_noncjk': 'Grants Non-CJK',
    'fsgrants_subtotal': 'Grants Subtotal',
    'fseast_asian_program_support_chinese': 'East Asian Program Support Chinese',
    'fseast_asian_program_support_japanese': 'East Asian Program Support Japanese',
    'fseast_asian_program_support_korean': 'East Asian Program Support Korean',
    'fseast_asian_program_support_noncjk': 'East Asian Program Support Non-CJK',
    'fseast_asian_program_support_subtotal': 'East Asian Program Support Subtotal',
    'fstotal_acquisition_budget': 'Total Acquisition Budget'
  },
  
  personnel: {
    'Library_Year.Library.library_name': 'Institution',
    'psfprofessional_chinese': 'Professional Chinese',
    'psfprofessional_japanese': 'Professional Japanese',
    'psfprofessional_korean': 'Professional Korean',
    'psfprofessional_eastasian': 'Professional East Asian',
    'psfprofessional_subtotal': 'Professional Total',
    'psfsupport_staff_chinese': 'Support Chinese',
    'psfsupport_staff_japanese': 'Support Japanese',
    'psfsupport_staff_korean': 'Support Korean',
    'psfsupport_staff_eastasian': 'Support East Asian',
    'psfsupport_staff_subtotal': 'Support Total',
    'psfstudent_assistants_chinese': 'Student Chinese',
    'psfstudent_assistants_japanese': 'Student Japanese',
    'psfstudent_assistants_korean': 'Student Korean',
    'psfstudent_assistants_eastasian': 'Student East Asian',
    'psfstudent_assistants_subtotal': 'Student Total',
    'psfothers': 'Others FTE',
    'psftotal': 'Total Personnel',
    'psfosacquisition': 'Outsourcing Acquisition',
    'psfosprocessing': 'Outsourcing Processing'
  },
  
  publicServices: {
    'Library_Year.Library.library_name': 'Institution',
    'pspresentations_subtotal': 'Presentations',
    'pspresentation_participants_subtotal': 'Presentation Participants',
    'psreference_transactions_subtotal': 'Reference Transactions',
    'pstotal_circulations_subtotal': 'Total Circulations',
    'pslending_requests_filled_subtotal': 'Lending Requests Filled',
    'pslending_requests_unfilled_subtotal': 'Lending Requests Unfilled',
    'psborrowing_requests_filled_subtotal': 'Borrowing Requests Filled',
    'psborrowing_requests_unfilled_subtotal': 'Borrowing Requests Unfilled'
  },
  
  electronic: {
    'Library_Year.Library.library_name': 'Institution',
    // One-time Computer Files
    'eonetime_computer_title_chinese': 'One-time Computer Titles Chinese',
    'eonetime_computer_title_japanese': 'One-time Computer Titles Japanese',
    'eonetime_computer_title_korean': 'One-time Computer Titles Korean',
    'eonetime_computer_title_noncjk': 'One-time Computer Titles Non-CJK',
    'eonetime_computer_title_subtotal': 'One-time Computer Titles Subtotal',
    'eonetime_computer_cd_chinese': 'One-time Computer CDs Chinese',
    'eonetime_computer_cd_japanese': 'One-time Computer CDs Japanese',
    'eonetime_computer_cd_korean': 'One-time Computer CDs Korean',
    'eonetime_computer_cd_noncjk': 'One-time Computer CDs Non-CJK',
    'eonetime_computer_cd_subtotal': 'One-time Computer CDs Subtotal',
    // Accompanied Computer Files
    'eaccompanied_computer_title_chinese': 'Accompanied Computer Titles Chinese',
    'eaccompanied_computer_title_japanese': 'Accompanied Computer Titles Japanese',
    'eaccompanied_computer_title_korean': 'Accompanied Computer Titles Korean',
    'eaccompanied_computer_title_noncjk': 'Accompanied Computer Titles Non-CJK',
    'eaccompanied_computer_title_subtotal': 'Accompanied Computer Titles Subtotal',
    'eaccompanied_computer_cd_chinese': 'Accompanied Computer CDs Chinese',
    'eaccompanied_computer_cd_japanese': 'Accompanied Computer CDs Japanese',
    'eaccompanied_computer_cd_korean': 'Accompanied Computer CDs Korean',
    'eaccompanied_computer_cd_noncjk': 'Accompanied Computer CDs Non-CJK',
    'eaccompanied_computer_cd_subtotal': 'Accompanied Computer CDs Subtotal',
    // Gift Computer Files
    'egift_computer_title_chinese': 'Gift Computer Titles Chinese',
    'egift_computer_title_japanese': 'Gift Computer Titles Japanese',
    'egift_computer_title_korean': 'Gift Computer Titles Korean',
    'egift_computer_title_noncjk': 'Gift Computer Titles Non-CJK',
    'egift_computer_title_subtotal': 'Gift Computer Titles Subtotal',
    'egift_computer_cd_chinese': 'Gift Computer CDs Chinese',
    'egift_computer_cd_japanese': 'Gift Computer CDs Japanese',
    'egift_computer_cd_korean': 'Gift Computer CDs Korean',
    'egift_computer_cd_noncjk': 'Gift Computer CDs Non-CJK',
    'egift_computer_cd_subtotal': 'Gift Computer CDs Subtotal',
    // Total Computer Files (Current Year)
    'etotal_computer_title_chinese': 'Total Computer Titles Chinese',
    'etotal_computer_title_japanese': 'Total Computer Titles Japanese',
    'etotal_computer_title_korean': 'Total Computer Titles Korean',
    'etotal_computer_title_noncjk': 'Total Computer Titles Non-CJK',
    'etotal_computer_title_subtotal': 'Total Computer Titles Subtotal',
    'etotal_computer_cd_chinese': 'Total Computer CDs Chinese',
    'etotal_computer_cd_japanese': 'Total Computer CDs Japanese',
    'etotal_computer_cd_korean': 'Total Computer CDs Korean',
    'etotal_computer_cd_noncjk': 'Total Computer CDs Non-CJK',
    'etotal_computer_cd_subtotal': 'Total Computer CDs Subtotal',
    // Previous Year Totals
    'eprevious_total_title_chinese': 'Previous Year Titles Chinese',
    'eprevious_total_title_japanese': 'Previous Year Titles Japanese',
    'eprevious_total_title_korean': 'Previous Year Titles Korean',
    'eprevious_total_title_noncjk': 'Previous Year Titles Non-CJK',
    'eprevious_total_title_subtotal': 'Previous Year Titles Subtotal',
    'eprevious_total_cd_chinese': 'Previous Year CDs Chinese',
    'eprevious_total_cd_japanese': 'Previous Year CDs Japanese',
    'eprevious_total_cd_korean': 'Previous Year CDs Korean',
    'eprevious_total_cd_noncjk': 'Previous Year CDs Non-CJK',
    'eprevious_total_cd_subtotal': 'Previous Year CDs Subtotal',
    // Grand Totals (Current + Previous)
    'egrand_total_title_chinese': 'Grand Total Titles Chinese',
    'egrand_total_title_japanese': 'Grand Total Titles Japanese',
    'egrand_total_title_korean': 'Grand Total Titles Korean',
    'egrand_total_title_noncjk': 'Grand Total Titles Non-CJK',
    'egrand_total_title_subtotal': 'Grand Total Titles Subtotal',
    'egrand_total_cd_chinese': 'Grand Total CDs Chinese',
    'egrand_total_cd_japanese': 'Grand Total CDs Japanese',
    'egrand_total_cd_korean': 'Grand Total CDs Korean',
    'egrand_total_cd_noncjk': 'Grand Total CDs Non-CJK',
    'egrand_total_cd_subtotal': 'Grand Total CDs Subtotal',
    // Electronic Indexes
    'eindex_electronic_title_chinese': 'Index Electronic Titles Chinese',
    'eindex_electronic_title_japanese': 'Index Electronic Titles Japanese',
    'eindex_electronic_title_korean': 'Index Electronic Titles Korean',
    'eindex_electronic_title_noncjk': 'Index Electronic Titles Non-CJK',
    'eindex_electronic_title_subtotal': 'Index Electronic Titles Subtotal',
    // Full-text Electronic
    'efulltext_electronic_title_chinese': 'Full-text Electronic Titles Chinese',
    'efulltext_electronic_title_japanese': 'Full-text Electronic Titles Japanese',
    'efulltext_electronic_title_korean': 'Full-text Electronic Titles Korean',
    'efulltext_electronic_title_noncjk': 'Full-text Electronic Titles Non-CJK',
    'efulltext_electronic_title_subtotal': 'Full-text Electronic Titles Subtotal',
    // Total Electronic Titles
    'etotal_electronic_title_chinese': 'Total Electronic Titles Chinese',
    'etotal_electronic_title_japanese': 'Total Electronic Titles Japanese',
    'etotal_electronic_title_korean': 'Total Electronic Titles Korean',
    'etotal_electronic_title_noncjk': 'Total Electronic Titles Non-CJK',
    'etotal_electronic_title_subtotal': 'Total Electronic Titles Subtotal',
    // Expenditures
    'etotal_expenditure_grandtotal': 'Total Expenditure Grand Total'
  },
  
  electronicBooks: {
    'Library_Year.Library.library_name': 'Institution',
    'ebooks_purchased_prev_titles_chinese': 'Purchased Titles Previous Chinese',
    'ebooks_purchased_prev_titles_japanese': 'Purchased Titles Previous Japanese',
    'ebooks_purchased_prev_titles_korean': 'Purchased Titles Previous Korean',
    'ebooks_purchased_prev_titles_noncjk': 'Purchased Titles Previous Non-CJK',
    'ebooks_purchased_prev_titles_subtotal': 'Purchased Titles Previous Subtotal',
    'ebooks_purchased_add_titles_chinese': 'Purchased Titles Add Chinese',
    'ebooks_purchased_add_titles_japanese': 'Purchased Titles Add Japanese',
    'ebooks_purchased_add_titles_korean': 'Purchased Titles Add Korean',
    'ebooks_purchased_add_titles_noncjk': 'Purchased Titles Add Non-CJK',
    'ebooks_purchased_add_titles_subtotal': 'Purchased Titles Add Subtotal',
    'ebooks_purchased_titles_chinese': 'Purchased Titles Total Chinese',
    'ebooks_purchased_titles_japanese': 'Purchased Titles Total Japanese',
    'ebooks_purchased_titles_korean': 'Purchased Titles Total Korean',
    'ebooks_purchased_titles_noncjk': 'Purchased Titles Total Non-CJK',
    'ebooks_purchased_titles_subtotal': 'Purchased Titles Total Subtotal',
    'ebooks_nonpurchased_titles_chinese': 'Non-Purchased Titles Chinese',
    'ebooks_nonpurchased_titles_japanese': 'Non-Purchased Titles Japanese',
    'ebooks_nonpurchased_titles_korean': 'Non-Purchased Titles Korean',
    'ebooks_nonpurchased_titles_noncjk': 'Non-Purchased Titles Non-CJK',
    'ebooks_nonpurchased_titles_subtotal': 'Non-Purchased Titles Subtotal',
    'ebooks_subscription_titles_chinese': 'Subscription Titles Chinese',
    'ebooks_subscription_titles_japanese': 'Subscription Titles Japanese',
    'ebooks_subscription_titles_korean': 'Subscription Titles Korean',
    'ebooks_subscription_titles_noncjk': 'Subscription Titles Non-CJK',
    'ebooks_subscription_titles_subtotal': 'Subscription Titles Subtotal',
    'ebooks_purchased_prev_volumes_chinese': 'Purchased Volumes Previous Chinese',
    'ebooks_purchased_prev_volumes_japanese': 'Purchased Volumes Previous Japanese',
    'ebooks_purchased_prev_volumes_korean': 'Purchased Volumes Previous Korean',
    'ebooks_purchased_prev_volumes_noncjk': 'Purchased Volumes Previous Non-CJK',
    'ebooks_purchased_prev_volumes_subtotal': 'Purchased Volumes Previous Subtotal',
    'ebooks_purchased_add_volumes_chinese': 'Purchased Volumes Add Chinese',
    'ebooks_purchased_add_volumes_japanese': 'Purchased Volumes Add Japanese',
    'ebooks_purchased_add_volumes_korean': 'Purchased Volumes Add Korean',
    'ebooks_purchased_add_volumes_noncjk': 'Purchased Volumes Add Non-CJK',
    'ebooks_purchased_add_volumes_subtotal': 'Purchased Volumes Add Subtotal',
    'ebooks_purchased_volumes_chinese': 'Purchased Volumes Total Chinese',
    'ebooks_purchased_volumes_japanese': 'Purchased Volumes Total Japanese',
    'ebooks_purchased_volumes_korean': 'Purchased Volumes Total Korean',
    'ebooks_purchased_volumes_noncjk': 'Purchased Volumes Total Non-CJK',
    'ebooks_purchased_volumes_subtotal': 'Purchased Volumes Total Subtotal',
    'ebooks_nonpurchased_volumes_chinese': 'Non-Purchased Volumes Chinese',
    'ebooks_nonpurchased_volumes_japanese': 'Non-Purchased Volumes Japanese',
    'ebooks_nonpurchased_volumes_korean': 'Non-Purchased Volumes Korean',
    'ebooks_nonpurchased_volumes_noncjk': 'Non-Purchased Volumes Non-CJK',
    'ebooks_nonpurchased_volumes_subtotal': 'Non-Purchased Volumes Subtotal',
    'ebooks_subscription_volumes_chinese': 'Subscription Volumes Chinese',
    'ebooks_subscription_volumes_japanese': 'Subscription Volumes Japanese',
    'ebooks_subscription_volumes_korean': 'Subscription Volumes Korean',
    'ebooks_subscription_volumes_noncjk': 'Subscription Volumes Non-CJK',
    'ebooks_subscription_volumes_subtotal': 'Subscription Volumes Subtotal',
    'ebooks_total_volumes': 'Total Volumes',
    'ebooks_total_titles': 'Total Titles'
  }
};

// Notes field names for each form (to be placed at bottom of Excel)
export const notesFields = {
  monographic: 'manotes',
  volumeHoldings: 'vhnotes',
  serials: 'snotes',
  otherHoldings: 'ohnotes',
  unprocessed: 'ubnotes',
  fiscal: 'fsnotes',
  personnel: 'psfnotes',
  publicServices: 'psnotes',
  electronic: 'enotes',
  electronicBooks: 'ebooks_notes'
};
