// Comprehensive field mappings for all 10 forms with frontend labels
// Notes fields are handled separately at the bottom of Excel exports

export const formFieldMappings = {
  monographic: {
    'Library_Year.Library.library_name': 'Institution',
    'mapurchased_titles_chinese': '01. Purchased Titles Chinese',
    'mapurchased_titles_japanese': '02. Purchased Titles Japanese',
    'mapurchased_titles_korean': '03. Purchased Titles Korean',
    'mapurchased_titles_noncjk': '04. Purchased Titles Non-CJK',
    'mapurchased_titles_subtotal': '05. Purchased Titles Subtotal',
    'mapurchased_volumes_chinese': '06. Purchased Volumes Chinese',
    'mapurchased_volumes_japanese': '07. Purchased Volumes Japanese',
    'mapurchased_volumes_korean': '08. Purchased Volumes Korean',
    'mapurchased_volumes_noncjk': '09. Purchased Volumes Non-CJK',
    'mapurchased_volumes_subtotal': '10. Purchased Volumes Subtotal',
    'manonpurchased_titles_chinese': '11. Non-Purchased Titles Chinese',
    'manonpurchased_titles_japanese': '12. Non-Purchased Titles Japanese',
    'manonpurchased_titles_korean': '13. Non-Purchased Titles Korean',
    'manonpurchased_titles_noncjk': '14. Non-Purchased Titles Non-CJK',
    'manonpurchased_titles_subtotal': '15. Non-Purchased Titles Subtotal',
    'manonpurchased_volumes_chinese': '16. Non-Purchased Volumes Chinese',
    'manonpurchased_volumes_japanese': '17. Non-Purchased Volumes Japanese',
    'manonpurchased_volumes_korean': '18. Non-Purchased Volumes Korean',
    'manonpurchased_volumes_noncjk': '19. Non-Purchased Volumes Non-CJK',
    'manonpurchased_volumes_subtotal': '20. Non-Purchased Volumes Subtotal',
    'matotal_titles': '21. Title Total',
    'matotal_volumes': '22. Volume Total'
  },
  
  volumeHoldings: {
    'Library_Year.Library.library_name': 'Institution',
    'vhprevious_year_chinese': '01. Previous Chinese',
    'vhprevious_year_japanese': '02. Previous Japanese',
    'vhprevious_year_korean': '03. Previous Korean',
    'vhprevious_year_noncjk': '04. Previous Non-CJK',
    'vhprevious_year_subtotal': '05. Previous Subtotal',
    'vhadded_gross_chinese': '06. Added Chinese',
    'vhadded_gross_japanese': '07. Added Japanese',
    'vhadded_gross_korean': '08. Added Korean',
    'vhadded_gross_noncjk': '09. Added Non-CJK',
    'vhadded_gross_subtotal': '10. Added Subtotal',
    'vhwithdrawn_chinese': '11. Withdrawn Chinese',
    'vhwithdrawn_japanese': '12. Withdrawn Japanese',
    'vhwithdrawn_korean': '13. Withdrawn Korean',
    'vhwithdrawn_noncjk': '14. Withdrawn Non-CJK',
    'vhwithdrawn_subtotal': '15. Withdrawn Subtotal',
    'vhgrandtotal': '16. Grand Total (Physical Vols)',
    'vhebooks_purchased_volume_total': '17. E-Books Purchased Volume Total',
    'vhoverall_grand_total': '18. Overall Grand Total'
  },
  
  serials: {
    'Library_Year.Library.library_name': 'Institution',
    's_epurchased_chinese': '01. Purchased Chinese (Electronic)',
    's_epurchased_japanese': '02. Purchased Japanese (Electronic)',
    's_epurchased_korean': '03. Purchased Korean (Electronic)',
    's_epurchased_noncjk': '04. Purchased Non-CJK (Electronic)',
    's_epurchased_subtotal': '05. Electronic Purchased Subtotal',
    'spurchased_chinese': '06. Purchased Chinese (Print)',
    'spurchased_japanese': '07. Purchased Japanese (Print)',
    'spurchased_korean': '08. Purchased Korean (Print)',
    'spurchased_noncjk': '09. Purchased Non-CJK (Print)',
    'spurchased_subtotal': '10. Print Purchased Subtotal',
    's_enonpurchased_chinese': '11. Non-Purchased Chinese (Electronic)',
    's_enonpurchased_japanese': '12. Non-Purchased Japanese (Electronic)',
    's_enonpurchased_korean': '13. Non-Purchased Korean (Electronic)',
    's_enonpurchased_noncjk': '14. Non-Purchased Non-CJK (Electronic)',
    's_enonpurchased_subtotal': '15. Electronic Non-Purchased Subtotal',
    'snonpurchased_chinese': '16. Non-Purchased Chinese (Print)',
    'snonpurchased_japanese': '17. Non-Purchased Japanese (Print)',
    'snonpurchased_korean': '18. Non-Purchased Korean (Print)',
    'snonpurchased_noncjk': '19. Non-Purchased Non-CJK (Print)',
    'snonpurchased_subtotal': '20. Print Non-Purchased Subtotal',
    's_etotal_chinese': '21. Total Chinese (Electronic)',
    's_etotal_japanese': '22. Total Japanese (Electronic)',
    's_etotal_korean': '23. Total Korean (Electronic)',
    's_etotal_noncjk': '24. Total Non-CJK (Electronic)',
    's_egrandtotal': '25. Electronic Grand Total',
    'stotal_chinese': '26. Total Chinese (Print)',
    'stotal_japanese': '27. Total Japanese (Print)',
    'stotal_korean': '28. Total Korean (Print)',
    'stotal_noncjk': '29. Total Non-CJK (Print)',
    'sgrandtotal': '30. Print Grand Total',
    'stotal_overall': '31. Overall Grand Total'
  },
  
  otherHoldings: {
    'Library_Year.Library.library_name': 'Institution',
    'ohmicroform_chinese': '01. Microform Chinese',
    'ohmicroform_japanese': '02. Microform Japanese',
    'ohmicroform_korean': '03. Microform Korean',
    'ohmicroform_noncjk': '04. Microform Non-CJK',
    'ohmicroform_subtotal': '05. Microform Subtotal',
    'ohcarto_graphic_chinese': '06. Cartographic and Graphic Materials Chinese',
    'ohcarto_graphic_japanese': '07. Cartographic and Graphic Materials Japanese',
    'ohcarto_graphic_korean': '08. Cartographic and Graphic Materials Korean',
    'ohcarto_graphic_noncjk': '09. Cartographic and Graphic Materials Non-CJK',
    'ohcarto_graphic_subtotal': '10. Cartographic and Graphic Materials Subtotal',
    'ohaudio_chinese': '11. Audio Chinese',
    'ohaudio_japanese': '12. Audio Japanese',
    'ohaudio_korean': '13. Audio Korean',
    'ohaudio_noncjk': '14. Audio Non-CJK',
    'ohaudio_subtotal': '15. Audio Subtotal',
    'ohfilm_video_chinese': '16. Video Chinese',
    'ohfilm_video_japanese': '17. Video Japanese',
    'ohfilm_video_korean': '18. Video Korean',
    'ohfilm_video_noncjk': '19. Video Non-CJK',
    'ohfilm_video_subtotal': '20. Video Subtotal',
    'ohdvd_chinese': '21. DVD Chinese',
    'ohdvd_japanese': '22. DVD Japanese',
    'ohdvd_korean': '23. DVD Korean',
    'ohdvd_noncjk': '24. DVD Non-CJK',
    'ohdvd_subtotal': '25. DVD Subtotal',
    'ohgrandtotal': '26. Grand Total'
  },
  
  unprocessed: {
    'Library_Year.Library.library_name': 'Institution',
    'ubchinese': '01. Unprocessed Chinese',
    'ubjapanese': '02. Unprocessed Japanese',
    'ubkorean': '03. Unprocessed Korean',
    'ubnoncjk': '04. Unprocessed Non-CJK',
    'ubtotal': '05. Unprocessed Total'
  },
  
  fiscal: {
    'Library_Year.Library.library_name': 'Institution',
    'fschinese_appropriations_monographic': '01. Chinese Appropriations Monographic',
    'fschinese_appropriations_serial': '02. Chinese Appropriations Serial',
    'fschinese_appropriations_other_material': '03. Chinese Appropriations Other Materials',
    'fschinese_appropriations_electronic': '04. Chinese Appropriations Electronic',
    'fschinese_appropriations_subtotal': '05. Chinese Appropriations Subtotal',
    'fschinese_appropriations_subtotal_manual': '05a. Chinese Appropriations Subtotal (Manual Entry)',
    'fsjapanese_appropriations_monographic': '06. Japanese Appropriations Monographic',
    'fsjapanese_appropriations_serial': '07. Japanese Appropriations Serial',
    'fsjapanese_appropriations_other_material': '08. Japanese Appropriations Other Materials',
    'fsjapanese_appropriations_electronic': '09. Japanese Appropriations Electronic',
    'fsjapanese_appropriations_subtotal': '10. Japanese Appropriations Subtotal',
    'fsjapanese_appropriations_subtotal_manual': '10a. Japanese Appropriations Subtotal (Manual Entry)',
    'fskorean_appropriations_monographic': '11. Korean Appropriations Monographic',
    'fskorean_appropriations_serial': '12. Korean Appropriations Serial',
    'fskorean_appropriations_other_material': '13. Korean Appropriations Other Materials',
    'fskorean_appropriations_electronic': '14. Korean Appropriations Electronic',
    'fskorean_appropriations_subtotal': '15. Korean Appropriations Subtotal',
    'fskorean_appropriations_subtotal_manual': '15a. Korean Appropriations Subtotal (Manual Entry)',
    'fsnoncjk_appropriations_monographic': '16. Non-CJK Appropriations Monographic',
    'fsnoncjk_appropriations_serial': '17. Non-CJK Appropriations Serial',
    'fsnoncjk_appropriations_other_material': '18. Non-CJK Appropriations Other Materials',
    'fsnoncjk_appropriations_electronic': '19. Non-CJK Appropriations Electronic',
    'fsnoncjk_appropriations_subtotal': '20. Non-CJK Appropriations Subtotal',
    'fsnoncjk_appropriations_subtotal_manual': '20a. Non-CJK Appropriations Subtotal (Manual Entry)',
    'fstotal_appropriations': '21. Total Appropriations',
    'fstotal_appropriations_manual': '21a. Total Appropriations (Manual Entry)',
    'fsendowments_chinese': '22. Endowments Chinese',
    'fsendowments_japanese': '23. Endowments Japanese',
    'fsendowments_korean': '24. Endowments Korean',
    'fsendowments_noncjk': '25. Endowments Non-CJK',
    'fsendowments_subtotal': '26. Endowments Subtotal',
    'fsendowments_subtotal_manual': '26a. Endowments Subtotal (Manual Entry)',
    'fsgrants_chinese': '27. Grants Chinese',
    'fsgrants_japanese': '28. Grants Japanese',
    'fsgrants_korean': '29. Grants Korean',
    'fsgrants_noncjk': '30. Grants Non-CJK',
    'fsgrants_subtotal': '31. Grants Subtotal',
    'fsgrants_subtotal_manual': '31a. Grants Subtotal (Manual Entry)',
    'fseast_asian_program_support_chinese': '32. East Asian Program Support Chinese',
    'fseast_asian_program_support_japanese': '33. East Asian Program Support Japanese',
    'fseast_asian_program_support_korean': '34. East Asian Program Support Korean',
    'fseast_asian_program_support_noncjk': '35. East Asian Program Support Non-CJK',
    'fseast_asian_program_support_subtotal': '36. East Asian Program Support Subtotal',
    'fseast_asian_program_support_subtotal_manual': '36a. East Asian Program Support Subtotal (Manual Entry)',
    'fstotal_acquisition_budget': '37. Total Acquisition Budget'
  },
  
  personnel: {
    'Library_Year.Library.library_name': 'Institution',
    'psfprofessional_chinese': '01. Professional Chinese',
    'psfprofessional_japanese': '02. Professional Japanese',
    'psfprofessional_korean': '03. Professional Korean',
    'psfprofessional_eastasian': '04. Professional East Asian',
    'psfprofessional_subtotal': '05. Professional Total',
    'psfsupport_staff_chinese': '06. Support Chinese',
    'psfsupport_staff_japanese': '07. Support Japanese',
    'psfsupport_staff_korean': '08. Support Korean',
    'psfsupport_staff_eastasian': '09. Support East Asian',
    'psfsupport_staff_subtotal': '10. Support Total',
    'psfstudent_assistants_chinese': '11. Student Chinese',
    'psfstudent_assistants_japanese': '12. Student Japanese',
    'psfstudent_assistants_korean': '13. Student Korean',
    'psfstudent_assistants_eastasian': '14. Student East Asian',
    'psfstudent_assistants_subtotal': '15. Student Total',
    'psfothers': '16. Others FTE',
    'psftotal': '17. Total Personnel',
    'psfosacquisition': '18. Outsourcing Acquisition',
    'psfosprocessing': '19. Outsourcing Processing'
  },
  
  publicServices: {
    'Library_Year.Library.library_name': 'Institution',
    'pspresentations_subtotal': '01. Presentations',
    'pspresentation_participants_subtotal': '02. Presentation Participants',
    'psreference_transactions_subtotal': '03. Reference Transactions',
    'pstotal_circulations_subtotal': '04. Total Circulations',
    'pslending_requests_filled_subtotal': '05. Lending Requests Filled',
    'pslending_requests_unfilled_subtotal': '06. Lending Requests Unfilled',
    'psborrowing_requests_filled_subtotal': '07. Borrowing Requests Filled',
    'psborrowing_requests_unfilled_subtotal': '08. Borrowing Requests Unfilled'
  },
  
  electronic: {
    'Library_Year.Library.library_name': 'Institution',
    // 1.1 One-time Computer Files
    'eonetime_computer_title_chinese': '1.1-01. One-time Computer Titles Chinese',
    'eonetime_computer_title_japanese': '1.1-02. One-time Computer Titles Japanese',
    'eonetime_computer_title_korean': '1.1-03. One-time Computer Titles Korean',
    'eonetime_computer_title_noncjk': '1.1-04. One-time Computer Titles Non-CJK',
    'eonetime_computer_title_subtotal': '1.1-05. One-time Computer Titles Subtotal',
    'eonetime_computer_cd_chinese': '1.1-01. One-time Computer CDs Chinese',
    'eonetime_computer_cd_japanese': '1.1-02. One-time Computer CDs Japanese',
    'eonetime_computer_cd_korean': '1.1-03. One-time Computer CDs Korean',
    'eonetime_computer_cd_noncjk': '1.1-04. One-time Computer CDs Non-CJK',
    'eonetime_computer_cd_subtotal': '1.1-05. One-time Computer CDs Subtotal',
    // 1.2 Accompanied Computer Files
    'eaccompanied_computer_title_chinese': '1.2-06. Accompanied Computer Titles Chinese',
    'eaccompanied_computer_title_japanese': '1.2-07. Accompanied Computer Titles Japanese',
    'eaccompanied_computer_title_korean': '1.2-08. Accompanied Computer Titles Korean',
    'eaccompanied_computer_title_noncjk': '1.2-09. Accompanied Computer Titles Non-CJK',
    'eaccompanied_computer_title_subtotal': '1.2-10. Accompanied Computer Titles Subtotal',
    'eaccompanied_computer_cd_chinese': '1.2-06. Accompanied Computer CDs Chinese',
    'eaccompanied_computer_cd_japanese': '1.2-07. Accompanied Computer CDs Japanese',
    'eaccompanied_computer_cd_korean': '1.2-08. Accompanied Computer CDs Korean',
    'eaccompanied_computer_cd_noncjk': '1.2-09. Accompanied Computer CDs Non-CJK',
    'eaccompanied_computer_cd_subtotal': '1.2-10. Accompanied Computer CDs Subtotal',
    // 1.3 Gift Computer Files
    'egift_computer_title_chinese': '1.3-11. Gift Computer Titles Chinese',
    'egift_computer_title_japanese': '1.3-12. Gift Computer Titles Japanese',
    'egift_computer_title_korean': '1.3-13. Gift Computer Titles Korean',
    'egift_computer_title_noncjk': '1.3-14. Gift Computer Titles Non-CJK',
    'egift_computer_title_subtotal': '1.3-15. Gift Computer Titles Subtotal',
    'egift_computer_cd_chinese': '1.3-11. Gift Computer CDs Chinese',
    'egift_computer_cd_japanese': '1.3-12. Gift Computer CDs Japanese',
    'egift_computer_cd_korean': '1.3-13. Gift Computer CDs Korean',
    'egift_computer_cd_noncjk': '1.3-14. Gift Computer CDs Non-CJK',
    'egift_computer_cd_subtotal': '1.3-15. Gift Computer CDs Subtotal',
    // 1.4 Total Computer Files (Current Year)
    'etotal_computer_title_chinese': '1.4. Total Computer Titles Chinese',
    'etotal_computer_title_japanese': '1.4. Total Computer Titles Japanese',
    'etotal_computer_title_korean': '1.4. Total Computer Titles Korean',
    'etotal_computer_title_noncjk': '1.4. Total Computer Titles Non-CJK',
    'etotal_computer_title_subtotal': '1.4. Total Computer Titles Subtotal',
    'etotal_computer_cd_chinese': '1.4. Total Computer CDs Chinese',
    'etotal_computer_cd_japanese': '1.4. Total Computer CDs Japanese',
    'etotal_computer_cd_korean': '1.4. Total Computer CDs Korean',
    'etotal_computer_cd_noncjk': '1.4. Total Computer CDs Non-CJK',
    'etotal_computer_cd_subtotal': '1.4. Total Computer CDs Subtotal',
    // 1.5 Previous Year Totals
    'eprevious_total_title_chinese': '1.5-16. Previous Year Titles Chinese',
    'eprevious_total_title_japanese': '1.5-17. Previous Year Titles Japanese',
    'eprevious_total_title_korean': '1.5-18. Previous Year Titles Korean',
    'eprevious_total_title_noncjk': '1.5-19. Previous Year Titles Non-CJK',
    'eprevious_total_title_subtotal': '1.5-19.1. Previous Year Titles Subtotal',
    'eprevious_total_cd_chinese': '1.5. Previous Year CDs Chinese',
    'eprevious_total_cd_japanese': '1.5. Previous Year CDs Japanese',
    'eprevious_total_cd_korean': '1.5. Previous Year CDs Korean',
    'eprevious_total_cd_noncjk': '1.5. Previous Year CDs Non-CJK',
    'eprevious_total_cd_subtotal': '1.5. Previous Year CDs Subtotal',
    // 1.6 Grand Totals (Current + Previous)
    'egrand_total_title_chinese': '1.6-20. Grand Total Titles Chinese',
    'egrand_total_title_japanese': '1.6-21. Grand Total Titles Japanese',
    'egrand_total_title_korean': '1.6-22. Grand Total Titles Korean',
    'egrand_total_title_noncjk': '1.6-23. Grand Total Titles Non-CJK',
    'egrand_total_title_subtotal': '1.6-23.1. Grand Total Titles Subtotal',
    'egrand_total_cd_chinese': '1.6. Grand Total CDs Chinese',
    'egrand_total_cd_japanese': '1.6. Grand Total CDs Japanese',
    'egrand_total_cd_korean': '1.6. Grand Total CDs Korean',
    'egrand_total_cd_noncjk': '1.6. Grand Total CDs Non-CJK',
    'egrand_total_cd_subtotal': '1.6. Grand Total CDs Subtotal',
    // 2.1 Electronic Indexes
    'eindex_electronic_title_chinese': '2.1-31. Index Electronic Titles Chinese',
    'eindex_electronic_title_japanese': '2.1-32. Index Electronic Titles Japanese',
    'eindex_electronic_title_korean': '2.1-33. Index Electronic Titles Korean',
    'eindex_electronic_title_noncjk': '2.1-34. Index Electronic Titles Non-CJK',
    'eindex_electronic_title_subtotal': '2.1-35. Index Electronic Titles Subtotal',
    // 2.2 Full-text Electronic
    'efulltext_electronic_title_chinese': '2.2-36. Full-text Electronic Titles Chinese',
    'efulltext_electronic_title_japanese': '2.2-37. Full-text Electronic Titles Japanese',
    'efulltext_electronic_title_korean': '2.2-38. Full-text Electronic Titles Korean',
    'efulltext_electronic_title_noncjk': '2.2-39. Full-text Electronic Titles Non-CJK',
    'efulltext_electronic_title_subtotal': '2.2-40. Full-text Electronic Titles Subtotal',
    // 2.3 Total Electronic Titles
    'etotal_electronic_title_chinese': '2.3. Total Electronic Titles Chinese',
    'etotal_electronic_title_japanese': '2.3. Total Electronic Titles Japanese',
    'etotal_electronic_title_korean': '2.3. Total Electronic Titles Korean',
    'etotal_electronic_title_noncjk': '2.3. Total Electronic Titles Non-CJK',
    'etotal_electronic_title_subtotal': '2.3. Total Electronic Titles Subtotal',
    // 3. Expenditures
    'etotal_expenditure_grandtotal': '3-41. Total Expenditure Grand Total'
  },
  
  electronicBooks: {
    'Library_Year.Library.library_name': 'Institution',
    // TITLES Section - Purchased (Previous/Add/Total structure)
    'ebooks_purchased_prev_titles_chinese': '01. Purchased Titles - Previous - Chinese',
    'ebooks_purchased_prev_titles_japanese': '02. Purchased Titles - Previous - Japanese',
    'ebooks_purchased_prev_titles_korean': '03. Purchased Titles - Previous - Korean',
    'ebooks_purchased_prev_titles_noncjk': '04. Purchased Titles - Previous - Non-CJK',
    'ebooks_purchased_prev_titles_subtotal': '05. Purchased Titles - Previous - Subtotal',
    'ebooks_purchased_add_titles_chinese': '01. Purchased Titles - Add - Chinese',
    'ebooks_purchased_add_titles_japanese': '02. Purchased Titles - Add - Japanese',
    'ebooks_purchased_add_titles_korean': '03. Purchased Titles - Add - Korean',
    'ebooks_purchased_add_titles_noncjk': '04. Purchased Titles - Add - Non-CJK',
    'ebooks_purchased_add_titles_subtotal': '05. Purchased Titles - Add - Subtotal',
    'ebooks_purchased_titles_chinese': '01. Purchased Titles - Total - Chinese',
    'ebooks_purchased_titles_japanese': '02. Purchased Titles - Total - Japanese',
    'ebooks_purchased_titles_korean': '03. Purchased Titles - Total - Korean',
    'ebooks_purchased_titles_noncjk': '04. Purchased Titles - Total - Non-CJK',
    'ebooks_purchased_titles_subtotal': '05. Purchased Titles - Total - Subtotal',
    // TITLES Section - Non-Purchased
    'ebooks_nonpurchased_titles_chinese': '06. Non-Purchased Titles - Chinese',
    'ebooks_nonpurchased_titles_japanese': '07. Non-Purchased Titles - Japanese',
    'ebooks_nonpurchased_titles_korean': '08. Non-Purchased Titles - Korean',
    'ebooks_nonpurchased_titles_noncjk': '09. Non-Purchased Titles - Non-CJK',
    'ebooks_nonpurchased_titles_subtotal': '10. Non-Purchased Titles - Subtotal',
    // TITLES Section - Subscription
    'ebooks_subscription_titles_chinese': '11. Subscription Titles - Chinese',
    'ebooks_subscription_titles_japanese': '12. Subscription Titles - Japanese',
    'ebooks_subscription_titles_korean': '13. Subscription Titles - Korean',
    'ebooks_subscription_titles_noncjk': '14. Subscription Titles - Non-CJK',
    'ebooks_subscription_titles_subtotal': '15. Subscription Titles - Subtotal',
    // VOLUMES Section - Purchased (Previous/Add/Total structure)
    'ebooks_purchased_prev_volumes_chinese': '16. Purchased Volumes - Previous - Chinese',
    'ebooks_purchased_prev_volumes_japanese': '17. Purchased Volumes - Previous - Japanese',
    'ebooks_purchased_prev_volumes_korean': '18. Purchased Volumes - Previous - Korean',
    'ebooks_purchased_prev_volumes_noncjk': '19. Purchased Volumes - Previous - Non-CJK',
    'ebooks_purchased_prev_volumes_subtotal': '20. Purchased Volumes - Previous - Subtotal',
    'ebooks_purchased_add_volumes_chinese': '16. Purchased Volumes - Add - Chinese',
    'ebooks_purchased_add_volumes_japanese': '17. Purchased Volumes - Add - Japanese',
    'ebooks_purchased_add_volumes_korean': '18. Purchased Volumes - Add - Korean',
    'ebooks_purchased_add_volumes_noncjk': '19. Purchased Volumes - Add - Non-CJK',
    'ebooks_purchased_add_volumes_subtotal': '20. Purchased Volumes - Add - Subtotal',
    'ebooks_purchased_volumes_chinese': '16. Purchased Volumes - Total - Chinese',
    'ebooks_purchased_volumes_japanese': '17. Purchased Volumes - Total - Japanese',
    'ebooks_purchased_volumes_korean': '18. Purchased Volumes - Total - Korean',
    'ebooks_purchased_volumes_noncjk': '19. Purchased Volumes - Total - Non-CJK',
    'ebooks_purchased_volumes_subtotal': '20. Purchased Volumes - Total - Subtotal',
    // VOLUMES Section - Non-Purchased
    'ebooks_nonpurchased_volumes_chinese': '21. Non-Purchased Volumes - Chinese',
    'ebooks_nonpurchased_volumes_japanese': '22. Non-Purchased Volumes - Japanese',
    'ebooks_nonpurchased_volumes_korean': '23. Non-Purchased Volumes - Korean',
    'ebooks_nonpurchased_volumes_noncjk': '24. Non-Purchased Volumes - Non-CJK',
    'ebooks_nonpurchased_volumes_subtotal': '25. Non-Purchased Volumes - Subtotal',
    // VOLUMES Section - Subscription
    'ebooks_subscription_volumes_chinese': '26. Subscription Volumes - Chinese',
    'ebooks_subscription_volumes_japanese': '27. Subscription Volumes - Japanese',
    'ebooks_subscription_volumes_korean': '28. Subscription Volumes - Korean',
    'ebooks_subscription_volumes_noncjk': '29. Subscription Volumes - Non-CJK',
    'ebooks_subscription_volumes_subtotal': '30. Subscription Volumes - Subtotal',
    // Grand Totals
    'ebooks_total_titles': '31. Total Titles',
    'ebooks_total_volumes': '32. Total Volumes'
  }
};

// Notes field names for each form (to be placed at bottom of Excel)
export const notesFields = {
  monographic: 'manotes',
  volumeHoldings: 'vhnotes',
  serials: 'snotes',
  otherHoldings: 'ohnotes',
  unprocessed: 'ubnotes',
  fiscal: 'fsnotes',
  personnel: 'psfnotes',
  publicServices: 'psnotes',
  electronic: 'enotes',
  electronicBooks: 'ebooks_notes'
};
