name: Deploy with Sequence Safety

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main]

jobs:
  pre-deploy-checks:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup test database
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        run: |
          npx prisma generate --schema=./prisma/schema
          npx prisma db push --schema=./prisma/schema
          
      - name: Run sequence health check
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        run: npm run db:check

  deploy:
    runs-on: ubuntu-latest
    needs: pre-deploy-checks
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      # Add your actual deployment steps here
      # Example for different platforms:
      
      # For Vercel:
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v25
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.ORG_ID }}
      #     vercel-project-id: ${{ secrets.PROJECT_ID }}
      
      # For Railway:
      # - name: Deploy to Railway
      #   uses: railway-deploy/railway-deploy@v1
      #   with:
      #     railway-token: ${{ secrets.RAILWAY_TOKEN }}
      
      # For custom deployment:
      # - name: Deploy to production
      #   run: |
      #     # Your deployment commands here
      #     echo "Deploying to production..."
      
  post-deploy-verify:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Verify deployment
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
        run: npm run db:verify
